# Hyperparameters for LSTM action recognition model

# Model Parameters
feature_dim: 2048
hidden_dim: 512
num_layers: 2
dropout: 0.7
bidirectional: True

# Training Parameters
lr: 0.0001
batch_size: 32
epochs: 10
sequence_length: 100
num_workers: 4
no_cuda: True # Set to True to disable CUDA even if available
