# Hyperparameters for LSTM action recognition model

# Model Parameters
feature_dim: 2048
hidden_dim: 256
num_layers: 2
dropout: 0.7
bidirectional: True

# Training Parameters
lr: 0.00001
batch_size: 16
epochs: 6
sequence_length: 30
num_workers: 4
no_cuda: True # Set to True to disable CUDA even if available
